# frozen_string_literal: true

source 'https://rubygems.org'

gem 'faraday'

group :development do
  gem 'guard'
  gem 'guard-rspec', require: false
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-rspec'
end
